use customer_behavior;


-- Q! What is the total revenue generated by ,ale s. female customers?
SELECT gender, SUM(purchase_amount_usd) as revenue
FROM customer
GROUP BY gender;


-- Q2 which customer used a discount but stil spent more than the average purchase amount
SELECT customer_id, purchase_amount_usd
FROM customer
WHERE discount_applied = 'Yes'
AND purchase_amount_usd >= (SELECT avg(purchase_amount_usd) FROM customer);


-- Q3 Which are the top 5 products with the highest review rating
SELECT item_purchased, round(AVG(review_rating),2) as "Average Product Rating"
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;


-- Q4 Compare the average purchase amounts between standards adn express shipping
select shipping_type, round(AVG(purchase_amount_usd),2)
FROM customer
WHERE shipping_type in ('Standard', 'Express')
GROUP BY shipping_type;


-- Q5 Do subscribed customers spend more? compare average spend and total revenue between subscribers and non-subscribers.
select subscription_status, COUNT(customer_id) as total_customers, round(AVG(purchase_amount_usd),2) as average_spending, round(SUM(purchase_amount_usd),2) as total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue, average_spending desc;


-- Q6 which 5 products had the highest purchases with discount applied
SELECT item_purchased, round((SUM(case when discount_applied = 'Yes' then 1 else 0 end)/COUNT(*)) * 100, 2) as discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate desc
LIMIT 5;


-- Q7 Segment customers into new, returning, and loyal based on their total number of previous purchases, and show the count of each segment
with customer_type as(
    select customer_id, previous_purchases,
    CASE 
        WHEN previous_purchases = 1 THEN "New"
        when previous_purchases BETWEEN 2 AND 10 then "Returning"  
        ELSE  "Loyal"
    END AS customer_segment
    FROM customer
)
SELECT customer_segment, COUNT(*) AS number_of_customers
FROM customer_type
GROUP BY customer_segment;


-- Q8 What are the top 3 most purchased products within each category.
with item_counts as (
    select category, item_purchased, COUNT(customer_id) as total_orders,
    row_number() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) as item_rank
    from customer
    GROUP BY category, item_purchased
)
SELECT item_rank, category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <= 3;


-- Q9 Are customers who are repeast buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status, COUNT(customer_id) as repeat_buyers
from customer
WHERE previous_purchases > 5
GROUP BY subscription_status;


-- Q10 what is the revenue contribution of each age group?
select age_group, SUM(purchase_amount_usd) as total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;
